project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

author: # Replace with team member names
  - name: Srilakshmi Venkatesan
  - name: Daniel Murong
  - name: Sriya Sridhar
  - name: Ryan Lee

website:
  title: the-pipe-operators
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.pdf  
      - text: Proposal
        href: proposal.qmd
      - text: EDA
        href: eda.qmd
      - text: About
        href: about.qmd
      - text: Contract
        href: contract.qmd

    right:
      - icon: github
        href: "https://github.com/sta199-f25/project-the-pipe-operators.git" 

format:
  html:
    theme: journal
