project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

author: # Replace with team member names
  - name: Name of team member 1 
  - name: Name of team member 2
  - name: Name of team member 3
  - name: Name of team member 4
  - name: ...

website:
  # Replace with team name
  title: Team name 
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.pdf  
      - text: Proposal
        href: proposal.qmd
      - text: About
        href: about.qmd
      - text: Contract
        href: contract.qmd
    right:
      - icon: github
        # Replace with link to GitHub repo
        href: "https://github.com/sta199-f25/" 

format:
  html:
    theme: 
      light: flatly
      dark: darkly
