project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

author: # Replace with team member names
  - name: Srilakshmi Venkatesan
  - name: Daniel Murong
  - name: Sriya Sridhar
  - name: Ryan Lee

website:
  title: the-pipe-operators
  favicon: resources/favicon.png
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.qmd
      - text: Proposal
        href: proposal.qmd
      - text: EDA
        href: eda.qmd
      - text: About
        href: about.qmd
      - text: Contract
        href: contract.qmd

    right:
      - icon: github
        href: "https://github.com/djmurong/math-performance-predictor-analysis.git"

format:
  html:
    theme: journal
